name: Pipeline Inteligente

on:

  workflow_dispatch:

  schedule:
    - cron: '0 2 * * *'

  push:

    branches:
      - 'feature/**'

    paths:
      - 'src/**'
      - '!src/docs/**'

jobs:

  job_gerador:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Gerar relatórios
        run: |
          mkdir saida_build
          echo "Relatorio 1 gerado com sucesso" > saida_build/relatorio1.txt
          echo "Relatorio 2 gerado com sucesso" > saida_build/relatorio2.txt

      - name: Upload artefato
        uses: actions/upload-artifact@v4
        with:
          name: meus-relatorios-oficiais
          path: saida_build/

  job_auditoria:

    needs: job_gerador

    runs-on: ubuntu-latest

    steps:

      - name: Download artefato
        uses: actions/download-artifact@v4
        with:
          name: meus-relatorios-oficiais

      - name: Listar arquivos
        run: ls -R

      - name: Mostrar relatório
        run: cat relatorio1.txt